/* eslint-disable import/prefer-default-export */
export const vials = [
  {
    itemId: "SEV213",
    cc: 2,
    outerDiameter: "12 mm",
    quantity: 100,
    imgClear: "/Images/pages/our-product/SEV213@2x.png",
    imgAmber: "/Images/pages/our-product/SEV213-AMB@2x.png",
    fluroTec: false,
  },
  {
    itemId: "SEV520",
    cc: 5,
    outerDiameter: "20 mm",
    quantity: 25,
    imgClear: "/Images/pages/our-product/SEV520@2x.png",
    imgAmber: "/Images/pages/our-product/SEV520-AMB@2x.png",
    fluroTec: false,
  },
  {
    itemId: "SEV1020",
    cc: 10,
    outerDiameter: "20 mm",
    quantity: 25,
    imgClear: "/Images/pages/our-product/SEV1020@2x.png",
    imgAmber: "/Images/pages/our-product/SEV1020-AMB@2x.png",
    fluroTec: true,
  },
  {
    itemId: "SEV20",
    cc: 20,
    outerDiameter: "20 mm",
    quantity: 10,
    imgClear: "/Images/pages/our-product/SEV20@2x.png",
    imgAmber: null,
    fluroTec: false,
  },
  {
    itemId: "SEV30",
    cc: 30,
    outerDiameter: "20 mm",
    quantity: 25,
    imgClear: "/Images/pages/our-product/SEV30@2x.png",
    imgAmber: "/Images/pages/our-product/SEV30-AMB@2x.png",
    fluroTec: true,
  },
  {
    itemId: "SEV50",
    cc: 50,
    outerDiameter: "20 mm",
    quantity: 25,
    imgClear: "/Images/pages/our-product/SEV50@2x.png",
    imgAmber: "/Images/pages/our-product/SEV50-AMB@2x.png",
    fluroTec: true,
  },
  {
    itemId: "SEV100",
    cc: 100,
    outerDiameter: "20 mm",
    quantity: 25,
    imgClear: "/Images/pages/our-product/SEV100@2x.png",
    imgAmber: "/Images/pages/our-product/SEV100-AMB@2x.png",
    fluroTec: true,
  },
];
